### ISSUE TITLE
What is "plug-in data", please?

### ISSUE THREAD

**Issue by mazesy** [dessant/clear-browsing-data#1]
I've been dealing with browsers for years and I understand everything this _Clear Browsing Data_ extension removes...except for the _plug-in data_ item. I've seen this term appear ever since Firefox 57 but to what does it actually correspond?! If people start inventing terms to describe what was previously explicit then where is this world going?!

**Comment by dessant** [comment]
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/browsingData/removePluginData

**Comment by 001101** [comment]
Could it be possible to just write a wikipage with any 'describtions' from the plugin for the specific browser and an example?

Because, if you believe it or not, users really use Local Index or don't want to purge all their Plugin Data away.
