### ISSUE TITLE
Feature Request: Cookie Whitelist

### ISSUE THREAD

**Issue by Ainson** [dessant/clear-browsing-data#11]
Hi and thanks for a very useful thing that I use constantly.

I just wish that some cookies could be left in place for sites that I want to stay logged in at.

Possible?

**Comment by dessant** [comment]
It should be possible if the `cookies` permission is requested. It would be an awesome feature to have, but it's unlikely I'll have time to implement the feature in the foreseeable future.

**Comment by Ainson** [comment]
Shame, but understand.

**Comment by dessant** [comment]
I'm closing this because I'll not have time to implement it. If anyone would like to work on this feature, please get in touch here.
