### ISSUE TITLE
Feature Request: add a visual effect after cleaning

### ISSUE THREAD

**Issue by sidbentifraouine** [dessant/clear-browsing-data#14]

**Comment by dessant** [comment]
Hi @sidbentifraouine! What do you mean by a visual effect, a notification?

**Comment by sidbentifraouine** [comment]
HI @dessant , yeah something like that.
https://cl.ly/2dfda7304a29
I was thinking about a popup "👌 Cleaned everything!" 🙂

**Comment by dessant** [comment]
A notification is already shown after the data is cleared, maybe you have turned the option off.

**Comment by dessant** [comment]
Let me know if you were thinking of something else.

**Comment by sidbentifraouine** [comment]
It was displaying the notification on my other monitor, my bad 😅, and thank you for your nice job ❤️
