### ISSUE TITLE
Lower the time period

### ISSUE THREAD

**Issue by KIMWW** [dessant/clear-browsing-data#17]
Congrats for this add-on (Firefox). Very useful. Thank you.
Could you let users decide how long they want the past time period to be? If not, can you make it lower than 1 hour. For example, 15 minutes...

**Comment by dessant** [comment]
Setting a custom time seems like an overkill, and it would require a date and time selector widget. Let's add for now a couple of options with less than 1 hour.

**Comment by KIMWW** [comment]
That's great, thanks.
