### ISSUE TITLE
Firefox Jump List cache not cleared

### ISSUE THREAD

**Issue by dave47** [dessant/clear-browsing-data#18]

**Comment by dessant** [comment]
The extension uses browser APIs, please open a bug report directly for Firefox: https://bugzilla.mozilla.org

**Comment by dave47** [comment]
see attachment
![Jump List](https://user-images.githubusercontent.com/18049384/59677112-1b8faa00-9197-11e9-9ad0-9144fae0f69d.png)

**Comment by dessant** [comment]
This is the relevant API you could mention in your bug report on Bugzilla: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browsingData/removeCache
