### ISSUE TITLE
Local storage isn't being cleared

### ISSUE THREAD

**Issue by siffegh** [dessant/clear-browsing-data#20]
**System**
* OS name: Windows
* OS version: 7 Pro SP1
* Browser name: Firefox
* Browser version: 68.01
* Extension version: 2.3.0

**Bug description**
Local storage isn't being cleared by the extension. Looking at FF Options > Privacy & Security > Cookies and Site Data > Manage Data, storage is not cleared until doing it inside the FF option:

![Screenshot_1](https://user-images.githubusercontent.com/18728013/62013117-7c2de180-b15c-11e9-9691-5ed8afe32827.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/18728013/62013118-7df7a500-b15c-11e9-8364-beb364b02f10.jpg)
![Screenshot_3](https://user-images.githubusercontent.com/18728013/62013120-8059ff00-b15c-11e9-883b-940a247a3029.jpg)

**Logs**
![Screenshot_4](https://user-images.githubusercontent.com/18728013/62013138-9c5da080-b15c-11e9-9462-ed27a6bbf459.jpg)
![Screenshot_5](https://user-images.githubusercontent.com/18728013/62013140-9ff12780-b15c-11e9-9ef1-ae2451ca7c31.jpg)

**Comment by dessant** [comment]
Are you sure that it is the local storage and not the cache? The storage column in the Firefox preferences also includes other data types. There is a known Firefox bug that prevents extensions from clearing data stored with the Cache API: https://bugzilla.mozilla.org/show_bug.cgi?id=1526246

Local storage is cleared on my part, you can test it with this demo: http://jsfiddle.net/ccatto/G2SyC/2/

**Comment by siffegh** [comment]
Not sure how to run/view that demo. Cache is being cleared (C:\Users\Administrator\AppData\Local\Mozilla\Firefox\Profiles\8k367gi5.NewTest). 

After clearing LS:
![Screenshot_1](https://user-images.githubusercontent.com/18728013/62101000-d6649a80-b261-11e9-8803-d3e041cb87a1.jpg)

Files also remain in C:\Users\Administrator\AppData\Roaming\Mozilla\Firefox\Profiles\8k367gi5.NewTest\storage\default:
![Screenshot_2](https://user-images.githubusercontent.com/18728013/62101003-d8c6f480-b261-11e9-9b71-81c1fcdbc902.jpg)

![Screenshot_3](https://user-images.githubusercontent.com/18728013/62101006-da90b800-b261-11e9-8b7d-7dca177f23d2.jpg)

**Comment by siffegh** [comment]
Cache folder - meant C:\Users\Administrator\AppData\Local\Mozilla\Firefox\Profiles\8k367gi5.NewTest\cache2.

**Comment by dessant** [comment]
It's hard to reproduce the issue without having step by step instructions, I have tried, but the data is cleared on my part. Please share step by step instructions with a jsfiddle that stores data only in local storage, and make sure to refresh the options page or devtools before checking if the data was deleted.

**Comment by dessant** [comment]
If you do manage to reproduce the issue in a controlled way, please also open an issue for Firefox, because if valid, this can only be a browser bug.
