### ISSUE TITLE
Bugs after updating to Firefox 71 beta

### ISSUE THREAD

**Issue by nadesco** [dessant/clear-browsing-data#21]
Since updating to the latest Firefox beta a couple of small bugs have shown up.
1. Any words in the search bar are no longer deleted as they were before. (In Data Types all boxes are checked except Browsing history, Download history and Saved Passwords.)
2. Even with "Show notification on success" disabled, I now get notifications any time I click on the tool bar icon. ("Clear all data types" is set to "From browser toolbar"). Whether the "notification on success' slider is enabled or disabled the result is the same.
CBD ver. 2.4.0
Mac 10.14.6
Thank you.

**Comment by dessant** [comment]
You must check Browsing history to have your previous search keywords deleted from the address bar dropdown, this should work the same way in all Firefox versions.

I cannot reproduce the second bug, the notification is not shown if the option is unchecked, regardless of how the clearing is initiated. It's possible that your Firefox profile has an issue and the extension cannot save the changed option in storage, try reproducing the issue with a new profile.

Let me know if you find a way to consistently reproduce the second bug, and I'll reopen the issue.

**Comment by nadesco** [comment]
It isn’t the address bar dropdown with previous search keywords, it’s the search bar to the right of the address bar with any new keywords I'd entered in the current browsing session which don’t delete. I don’t remember which box needs to be checked for those keywords to be deleted but that function stopped after the update. Anyway, like the second bug it’s probably something to do with the profile so will try it in a new one when I get time. Thanks for your reply.
