### ISSUE TITLE
Options: One click clean all options selected.

### ISSUE THREAD

**Issue by dougg0k** [dessant/clear-browsing-data#27]
Hello,

I would like to request a feature, maybe by having an additional configuration to allow only by clicking in the red icon, it would clear all options that I had selected in the Options menu.

I think it could make this extension more complete with this option.

Thanks!

**Comment by dessant** [comment]
Hi, it's already possible to clear the enabled data types with a single click, set "Clear all data types" to "From browser toolbar".
