### ISSUE TITLE
Secure erasing

### ISSUE THREAD

**Issue by TheRedSpy15** [dessant/clear-browsing-data#3]
Helps a lot with privacy / security, and will help it standout from private tabs, as well as other extensions

**Comment by dessant** [comment]
By secure erasing you mean overwriting the data?

**Comment by dessant** [comment]
https://www.kingston.com/us/community/articledetail/articleid/29539

There is no easily accessible and safe way to erase specific files from SSD drives, the methods used for hard drives are ineffective for SSDs.

Even if there would be a reliable way to shred specific files, that is not always how Firefox stores browsing data. Some data types are just entries in a local database, at least that's the case with history and cookies.

I like the feature in general, but considering everything above, it's not feasible to implement truly secure erasing for these data types that just works on any device supported by Firefox.
