### ISSUE TITLE
Show all data types in pop-up, not just the selected ones

### ISSUE THREAD

**Issue by akwala** [dessant/clear-browsing-data#30]
**Is your feature request related to a problem? Please describe.**
Despite selecting a subset of the data types I usually want cleared, I occasionally want to clear a data type that is not among the selected. The extension doesn't provide a way to do this without having to temporarily modify the options.

**Describe the solution you'd like**
Use the selected data types when clearing "All data types" but show all data types (including those not selected) in the pop-up. 

Nice to have: a boolean option to control whether all or just the selected data types appear in the pop-up.

**Describe alternatives you've considered**
--

**Additional context**
--

**Comment by dessant** [comment]
Thanks for the feature request, let's track this here: https://github.com/dessant/clear-browsing-data/issues/31
