### ISSUE TITLE
Documentation is unclear on what "All Data Types" does.

### ISSUE THREAD

**Issue by redhermes** [dessant/clear-browsing-data#33]
**System**
* OS name: Windows
* OS version: 10
* Browser name: Firefox
* Browser version: na
* Extension version: na

**Bug description**
From the documentation it is unclear if the All Data Types button will in fact delete all the data type, or if it will deleted the selected data types. Please explain the actions taken and add to the documentation and/or website.

**Logs**
NA

BTW: Nice job on extension!.

**Comment by dessant** [comment]
Hi @redhermes, the All Data Types button will only clear enabled data types that are otherwise individually listed under the button.

**Comment by rgpublic** [comment]
+1 This should really be included in the documentation or reworded to "Selected data types" or "Enabled data types". Needed to look here on GitHub to find this out.

**Comment by dessant** [comment]
Issue tracked at https://github.com/dessant/clear-browsing-data/issues/40.
