### ISSUE TITLE
Cookies not deleted in Firefox

### ISSUE THREAD

**Issue by Ainson** [dessant/clear-browsing-data#37]
I've used CBD for years, but checking Firefox settings now, I see cookies still remain, even if CBD is set to delete cookies from all time.

- I've deleted cookies.sqlite to make a new one in case it was corrupted
- There is plenty of space on the disk

Any ideas?

CBD 3.2.0
Firefox 92
Windows 7 (64)

**Comment by dessant** [comment]
You're probably seeing this issue: https://github.com/dessant/clear-browsing-data/issues/13

A workaround is to disable the Cache API by setting `dom.caches.enabled` to `false` in `about:config`, manually clearing any leftover data, and restarting the browser. Please let me know if your issue still persists after doing that.

**Comment by Ainson** [comment]
This seems to have helped as sometimes all cookies are gone now, but other times some remain, and can only be gotten rid of manually. (I'm refreshing Firefox' settings page to make sure it's not just a display issue)
