### ISSUE TITLE
Surfing data is not deleted from the "\Data\profile\storage\default"

### ISSUE THREAD

**Issue by AlexanderGasman** [dessant/clear-browsing-data#39]
Hi! I have portable Firefox. After clicking the button with all the selected Data Types, the surfing data is not deleted from the folder: \Data\profile\storage\default. 
Can this be fixed?

**Bug description**

**Logs**

```
// REPLACE WITH LOGS
```

**Comment by dessant** [comment]
Hi Alex, just noticed your message on PayPal, thanks a lot for the donation!

Regarding this issue, the bad news is that the browsingData API in Firefox has several bugs, you will see data left behind in certain cases, and also possible data loss. See this issue for details: https://github.com/dessant/clear-browsing-data/issues/13

I've written an article about the issues that should give you a better idea of the state of the API in Firefox.
https://armin.dev/blog/2019/03/firefox-extensions-browsing-data-security/

There is nothing extension developers can do until these issues are present in Firefox. If removing this data is important for your online safety, I would advise you against using any extension that deletes browsing data in Firefox, and only remove data using the built-in cleaner from the browser's settings.
