### ISSUE TITLE
"Something went wrong. The selected browsing data has not been cleared."

### ISSUE THREAD

**Issue by joespr** [dessant/clear-browsing-data#4]
Got this message. Have been using current Clear Browsing Data on FF successfully since it came out on FF Quantum. Just got this error message for the first time. ( Got it after reading website The Intercept: https://firstlook.org/theintercept/ which I have done without trouble for a long time. )

I am on FF 57.0.4 (64 bit) on Ubuntu.

![firefox_clearbrowsingdata_20180119](https://user-images.githubusercontent.com/35619983/35179959-483187d6-fd5a-11e7-9cb5-c04b09b78807.png)

**Comment by dessant** [comment]
Thanks for the report. Which data type have you been trying to clear?

**Comment by joespr** [comment]
Yes, 2.0.0. I always have all Data Items checked, to clear everything.

**Comment by dessant** [comment]
It must be one of the newly enabled data types: IndexedDB or Local Storage. Please disable them, then enable them one by one and check which one produces the error.

The browser console could also be checked for more descriptive errors, open it with Ctrl+Shift+J, then see if anything useful is printed out as you clear the data types.

**Comment by joespr** [comment]
It's IndexDB Data that causes the error. 

from the browser console:

[Exception... "Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIQuotaManagerService.clearStoragesForPrincipal]"  nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame :: chrome://browser/content/ext-browsingData.js :: clearIndexedDB/</</< :: line 103"  data: no]  (unknown)
	clearIndexedDB/</</< chrome://browser/content/ext-browsingData.js:103:23
	clearIndexedDB/</< chrome://browser/content/ext-browsingData.js:102:25
Error: An unexpected error occurred  background.bundle.js:1:19407

Hope this is helpful.

**Comment by dessant** [comment]
Yes, thanks a lot, this will be valuable.

It's a bit strange because it works on my part both on Windows and Linux, maybe some profile change triggers the Firefox bug. Could you also make a test by installing it in a new Firefox profile?

**Comment by joespr** [comment]
Yes, it's odd, This has worked flawlessly for some time. 
I will try tomorrow.

**Comment by dessant** [comment]
That will be great. You're seeing the error only now because the latest version of the extension has been released today, enabling the handling of IndexedDB.

**Comment by joespr** [comment]
I created a new FF profile and installed the plugin, set to remove all datatypes, got no error.
Hope this is helpful.

**Comment by Przbl** [comment]
Fresh profile works for me, too. 
I have one profile where I migrated from an earlier Firefox version and afterwards installed this addon. 
With this I get this error, too, but in this case the Local Storage is the culprit.

**Comment by dessant** [comment]
This looks like a bug in Firefox, please open an issue on their bug tracker and share the details you've got so far. They'll be able to guide you further to find what causes the issue in older profiles.

https://bugzilla.mozilla.org/

**Comment by joespr** [comment]
I have the same issue, started recently when Firefox 67.0 released. Worked flawlessly for a long time previously. Ubuntu Linux 18.04.2.
