### ISSUE TITLE
Cookies clearing issue in private browsing?

### ISSUE THREAD

**Issue by logusergithub** [dessant/clear-browsing-data#42]
**System**

* OS name: [Windows]
* OS version: [10 21H2]
* Browser name: [Firefox]
* Browser version: [97]
* Extension version: [3.2.0]

To reproduce the issue: new profile, install 'Clear Browsing Data' and 'Cookie Quick Manager', new private browsing window or 'Always use private browsing mode'. Doesn't matter Firefox's ETP normal, strict or custom mode. CBD: all data types selected, close all tabs, 'All time' range. 
According to 'Cookie Quick Manager' current 'Context cookies (private browsing)' are not cleared. After a few tries it seems to me that many other similar extensions also have the same behavior (only in private browsing) except for example 'Cookie Autodelete'. 
https://i.postimg.cc/8C9dZ7tb/Cookies.png

I don't know if there is actually a issue but in case I reported it. Thanks.

Update: only if the 'All time' option is chosen.

**Comment by dessant** [comment]
The browsingData API is poorly implemented in Firefox, extensions cannot properly fix these issues.

https://github.com/dessant/clear-browsing-data/issues/13
https://armin.dev/blog/2019/03/firefox-extensions-browsing-data-security/
