### ISSUE TITLE
Clear Browsing-data - problem with notification window in bottom right of screen always pops up and I have it off

### ISSUE THREAD

**Issue by geewizzy** [dessant/clear-browsing-data#43]
**System**

* OS name: [e.g. Windows, Ubuntu]
* OS version: [e.g. 10]
* Browser name: [e.g. Chrome, Firefox]
* Browser version: [e.g. 60]
* Extension version: [e.g. 1.0.0]

**Bug description**

**Logs**

```
// REPLACE WITH LOGS
```

**Comment by dessant** [comment]
Please fill out the issue template, or at least share a screenshot. Does it show an error, or is it a notification about a successful data deletion?

**Comment by dessant** [comment]
The error is shown because your data is no longer being cleaned. Which version of Firefox are you using?

**Comment by dessant** [comment]
It means something has started causing an error during data deletion and the extension is warning you. Have you modified an option in `about:config` recently?

**Comment by dessant** [comment]
There must be an error with more details in the browser console, please open it with Ctrl+Shift+J and press the extension button to see the logged exception.

**Comment by geewizzy** [comment]
with - browser console, please open it with Ctrl+Shift+J    - iget this look at screensho
![2022-04-08_060705](https://user-images.githubusercontent.com/13062238/162414839-00001f05-0b23-4f89-b2ac-ce7335003753.jpg)
t

**Comment by dessant** [comment]
Your screenshot does not show the browser console.

**Comment by geewizzy** [comment]
![2022-04-08_062147](https://user-images.githubusercontent.com/13062238/162417095-d1a83a05-776e-4b51-8df7-d2081b8f4a28.jpg)

**Comment by dessant** [comment]
It tools like you have discovered a browser bug, or the modifications you have made to Firefox broke the extension API. You could try testing the extension with a fresh Firefox profile that has not been customized, and possibly report the issue to Mozilla if the error persists.

https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles

I have tested the extension with the latest Firefox version, and I could not reproduce the issue.

**Comment by geewizzy** [comment]
hey thanks for your time it shocked me that you up at this time - have a great day
