### ISSUE TITLE
Feature Request - Ability to clear all data using a direct link to call the Addon API, Add Custom User Set Timer to clear Automatically

### ISSUE THREAD

**Issue by mikec7000** [dessant/clear-browsing-data#44]
It would be so amazing if you added a function to clear "All Data Types" by calling a direct link to the extension so I can use it in a script and when called it tells the add-on to clear the data whenever it is called. You can also make a button that is embedded in each website html page so when I click it it tells the extension to clear "All Data Types" by clicking an HTML element that is compatible with automation programs, since currently the only way to delete data is clicking the eraser where only you can touch html elements.

Also I would also like to see a timer function bult-in that you can customized in seconds, when activated it automatically clears "All data types" when it reaches the countdown setting specified.

**Comment by dessant** [comment]
This project is for people, not bots.

**Comment by mikec7000** [comment]
You don't have to act like an ass because it will not take you a long way
into your programming career and hurt your reputation. It was just a
suggestion including the timer setting so I can delete trackers over time
automatically with a timer. I work in tech management and have a
programming team and you acting like this so disrespectful and such sour
taste I would not recommend you to amy company Mr. Sebastian. My life
lesson to you is think before you write something and the whole story in
place.

Take care

**Comment by dessant** [comment]
My reputation is not hurt by refusing to do free work for a spammer. I know exactly how you use the extension, do yourself a favor and remove it from your automated toolset.
