### ISSUE TITLE
What options must be selected to mimic the Firefox "Clear Data" settings

### ISSUE THREAD

**Issue by nollinvoyd** [dessant/clear-browsing-data#45]
Firefox 100.2

I had a problem with the Walmart website not loading, just a momentary flash of display, then a blank page, except for something regarding images on the lower left of the screen, what you normally see when a page is loading.

I went to the Firefox support forum and it was suggested that I clear my cache and cookies, which I had already done with your addon (Data Types selected:  Cookies; Cached images and files, and reload active tab) but it did not remedy the situation.

The "Clear Data" option in Firefox settings fixed it.

What are the options I should be enabling in "Clear Browsing Data" to achieve the same results?

**Comment by dessant** [comment]
I think you have experienced this Firefox bug: https://github.com/dessant/clear-browsing-data/issues/13

https://armin.dev/blog/2019/03/firefox-extensions-browsing-data-security/#data-saved-with-the-cache-api-is-not-cleared
