### ISSUE TITLE
Delete other add-on information.

### ISSUE THREAD

**Issue by oklokl** [dessant/clear-browsing-data#46]
**System**

* OS name: [e.g. Windows, Ubuntu] Windows10
* OS version: [e.g. 10] Version 10.0.19044.1889] home kor insider
* Browser name: [e.g. Chrome, Firefox] Firefox
* Browser version: [e.g. 60] 103.0.2
* Extension version: [e.g. 1.0.0] 3.2.0

**Bug description**

**Logs**

```
// REPLACE WITH LOGS
```
https://support.mozilla.org/en-US/questions/1385827
I have described my bug story here.

3 Bookmarks created by individuals
https://addons.mozilla.org/en/firefox/addon/syncmarx/?src=search
syncmarx

https://addons.mozilla.org/en-US/firefox/addon/fvd-synchronizer/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search
EverSync Bookmarks
This bookmark login will be canceled and all data will be lost.
So I tried contacting the developer. No answers.

Actually, it may not be a bug. However. It's uncomfortable.
I'm not good at English, so I use Google Translate.
So there is no answer.

**Comment by dessant** [comment]
If I understand correctly, Firefox Sync has deleted your bookmarks on a second device after you've cleared your bookmarks. Issues related to syncing bookmarks are not caused by this extension.
