### ISSUE TITLE
Req: add a time span longer than 4 weeks (but shorter than eternity)

### ISSUE THREAD

**Issue by Przbl** [dessant/clear-browsing-data#5]
In the option's "Miscellaneous" section the longest time-span for clearing the data apart "from the beginning of time" is "from the past 4 weeks". Would it be possible to add a span in between, like "1 year" or "2 years"?

Background of this request is:
I edited the _creationTime_ of some cookies to never loose them when using the clear-browsing-data addon and in the addon I set the time to "4 weeks". 
But when there are still unwanted cookies when I close Firefox and don't use this browser for 4 weeks (happens rarely in my case, but still) this concept breaks because the unwanted cookies aren't deleted, because they are older than 4 weeks. So a ridiculous long time-span like 1 or 2 years would help in this case.

**Comment by dessant** [comment]
This could be useful, I'll add 3 months, 6 months and 1 year.

**Comment by Przbl** [comment]
Sounds great, thanks!
