### ISSUE TITLE
Local storage is not cleared on Firefox 116.02

### ISSUE THREAD

**Issue by KWRuppert** [dessant/clear-browsing-data#54]
**System**

* OS name: Windows
* OS version: 10
* Browser name: Firefox
* Browser version: 116.02
* Extension version: 4.0

**Bug description**
Local Storage Data = Local Storage =All Files in  ...\Firefox\Profiles\42eeo3rr.default-release\storage\default\*
When I try to delete the Local Storage Data with the extension, the files not belonging to extensions(name is starting with moz-extensions+++....) are not removed.

When I use Ctrl-Shift-Delete in the browser and select "Offline Website Data" the remove is succesfull.

Have an Idea??

greetings Klaus

**Logs**

1691599670328	addons.webextension.{ce9f4b1f-24b8-4e9a-9051-b9e472b1b2f2}	WARN	pluginData has been deprecated (along with Flash plugin support)

**Comment by dessant** [comment]
It's an upstream bug, the browsingData API is unreliable in Firefox, please see https://github.com/dessant/clear-browsing-data/issues/23 and https://github.com/dessant/clear-browsing-data/issues/13.
