### ISSUE TITLE
Setting the time the notification is displayed

### ISSUE THREAD

**Issue by TheOneBehindYou** [dessant/clear-browsing-data#8]
Hi,
all is said in the title!
It could be nice to ad an option for the user to chose the amount of time the notification "cleared success" is displayed.
Thanks.

**Comment by dessant** [comment]
Hi, this sounds reasonable, thanks for bringing it up! We also have the needed API: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/notifications/clear

Though I'd like to have a couple of predefined values that you can choose from, not an arbitrary number of seconds.

It would look something like this:

Clear notifications:

* 4 seconds
* 10 seconds
* 30 seconds
* Never

**Comment by dessant** [comment]
After some more thinking, just removing the success notification after 6 seconds may be enough, I don't yet see a need to configure the success notification timeout, what's important is for it to be automatically removed. Error notifications will remain unchanged and stay in the notification feed until the user dismisses them.
