### ISSUE TITLE
Add reload tab option

### ISSUE THREAD

**Issue by gandaldf** [dessant/clear-browsing-data#9]
Hi! First of all thank you for your work! I think your extension is one of the most complete around and the fact that's available for all platform and three browsers makes it simply great!
I'd have just a request about a feature that could be useful... I'd like to have an auto-refresh of the current active tab or all the opened tabs after the cleaning is done; maybe making its behaviour optionable in the settings panel.
What do you think?

**Comment by dessant** [comment]
Hi! Thanks, I'm glad you find the extension useful! :yum: 

What is your main use case for reloading the tabs? Web dev?

**Comment by gandaldf** [comment]
Yeah absolutely... I use it for web dev so it help, when I'm debugging an app, to quickly reset everything and reload the page.

**Comment by dessant** [comment]
Sounds useful, I'll look into adding the feature.

**Comment by gandaldf** [comment]
Thank you very much!

**Comment by dessant** [comment]
The next release will add options for closing and reloading tabs, visit the extension's options to configure the new feature.

ref https://github.com/dessant/clear-browsing-data/commit/62b780d04cfe234372eb84a84cd26b2f3a02bfd8
